[versions]
androidGradlePlugin = "8.1.0"
kotlin = "1.9.0"

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
